### ISSUE TITLE
hashable-1.2.6.1 doesn't build on GHC 8.2.1-rc2

### ISSUE THREAD

**Issue by glguy** [tibbe/hashable#143]
The hashable-1.2.6.1 release advertises a base package upper bound that includes GHC 8.2.1-rc2 but the most recent changes aren't supported.

```
Building library for hashable-1.2.6.1..
[1 of 4] Compiling Data.Hashable.Class ( Data/Hashable/Class.hs, dist/build/Data/Hashable/Class.o )

Data/Hashable/Class.hs:114:32: error:
    Module
    ‘Type.Reflection.Unsafe’
    does not export
    ‘typeRepFingerprint’
    |
114 | import Type.Reflection.Unsafe (typeRepFingerprint)
    |                                ^^^^^^^^^^^^^^^^^^
```

**Comment by glguy** [comment]
I've lowered the base bound of the 1.2.6.1 release on Hackage so that builds using hashable will be able to succeed as a temporary fix.

**Comment by RyanGlScott** [comment]
@glguy, see #140 and #142. This was a relatively recent change (https://git.haskell.org/ghc.git/commit/88263f93e0f3add38f925d5afb799eee8df32606) that only just landed in the GHC 8.2 branch - @hvr's [Ubuntu PPA build](https://launchpad.net/~hvr/+archive/ubuntu/ghc) of GHC 8.2 didn't rebuild with this commit until yesterday.

**Comment by glguy** [comment]
That makes sense. It sounds like the package doesn't need any changes then, and once a new release candidate comes out the bound can be raised.

**Comment by RyanGlScott** [comment]
Unfortunately, limiting the upper version bounds has the side effect of breaking all Travis builds that use that PPA to get GHC 8.2, since it's more recent than rc2: https://travis-ci.org/foxik/hashmap/jobs/218461746

**Comment by glguy** [comment]
Yes, I'm talking to @hvr about his PPA presently
